<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_FORM_ID_alter().
 */

/**
 * Form alter for creation of "Freiwillige"
 */
function form_freiwillige_form_node_freiwillige_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //drupal_set_message('test1');
  //$form['field_initiative']['#disabled']= TRUE;
  //$form['field_beschreibung_stelle']['#title'] = t('Beschreibung');
  $form['actions']['submit']['#value'] = t('Abschicken');
  $form['revision_information']['#access'] = FALSE;
  $form['actions']['preview']['#access'] = FALSE;
  $form['actions']['submit']['#submit'][] = 'callback_set_redirect';
  //$form['field_beschreibung']['#type'] = 'textarea';
  // Modification for the form with the given form ID goes here. For example, if
  // FORM_ID is "user_register_form" this code would run only on the user
  // registration form.

  // Add a checkbox to registration form about agreeing to terms of use.
  //$form['terms_of_use'] = [
  //  '#type' => 'checkbox',
  //  '#title' => t("I agree with the website's terms and conditions."),
  //  '#required' => TRUE,
  //];
}
function callback_set_redirect($form, FormStateInterface $form_state) {
  form_freiwillige_send_mail();
  $form_state->setRedirect('<front>');
  drupal_get_messages('status');
  //To override message
  drupal_set_message('Schön, dass Du dich engagieren willst! Wir werden uns bald bei dir melden.');
  return;
}
/**
 *  Send email to team
 */
function form_freiwillige_send_mail(){
  $send_mail = new \Drupal\Core\Mail\Plugin\Mail\PhpMail(); // this is used to send HTML emails
  $from = 'kontakt@zeig-initiative.at';
  $to = 'kontakt@zeig-initiative.at';
  $message['headers'] = array(
  'content-type' => 'text/html',
  'MIME-Version' => '1.0',
  'reply-to' => $from,
  'from' => 'sender name <'.$from.'>'
  );
  $message['to'] = $to;
  $message['subject'] = "Ein neuer Freiwilliger hat sich eingetragen";

  $message['body'] = 'Unter dem Link https://www.zeig-initiative.at/freiwillige_uebersicht kann der Freiwillige einer Initiative zugewiesen werden.';

  $send_mail->mail($message);
}


/**
 *  Node alter for "Freiwillige"
 */

function hook_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  print('test');
  $type = $node->bundle();
  if ($op == 'view') {
    return NODE_ACCESS_DENY;
    if ($node->type == 'freiwillige'){
      drupal_set_message('test');
      if ($account->uid == $node->uid) {
        return NODE_ACCESS_ALLOW;
      }
      else {
        return NODE_ACCESS_DENY;
      }
    }
  }
}
