<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Form alter for creation of "offene Stelle"
 */
function form_initiativen_mitarbeiter_form_node_initiativen_mitarbeiter_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //drupal_set_message('test1');
  //$form['field_initiative']['#disabled']= TRUE;
  //$form['field_beschreibung_stelle']['#title'] = t('Beschreibung');
  $form['revision_information']['#access'] = FALSE;
  $form['actions']['preview']['#access'] = FALSE;

  $user = \Drupal::currentUser();
  // TODO: redirect to User profile
  // $url = Url::fromUri('internal:/user/'.$user->uid);
  // $form_state->setRedirectUrl($url);

  //$form['field_beschreibung_stelle']['#title'] = 'OMG';
  //$form['field_beschreibung']['#type'] = 'textarea';
  // Modification for the form with the given form ID goes here. For example, if
  // FORM_ID is "user_register_form" this code would run only on the user
  // registration form.

  // Add a checkbox to registration form about agreeing to terms of use.
  //$form['terms_of_use'] = [
  //  '#type' => 'checkbox',
  //  '#title' => t("I agree with the website's terms and conditions."),
  //  '#required' => TRUE,
  //];

  //Check if user has created an initiative already
  $id=$user->id();
  $user = \Drupal\user\Entity\User::load($id);
  $initiative = $user->field_meine_in->entity;

  if($initiative){
  }
  else{
    drupal_set_message('Bitte erstelle erst deine Initiative!');
    $form['actions']['submit']['#access'] = FALSE;
  }

}

// Write initiative into Offene Stelle programmatically
function form_initiativen_mitarbeiter_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'initiativen_mitarbeiter') {
          $node_storage = \Drupal::entityManager()->getStorage('node');
          // Loading the node offene stellen
          $node = $node_storage->load($entity->id());
          // Get node title
          //$title_initiative = $node->get('title')->value;
          // Get user
          $user = \Drupal::currentUser();
          $id=$user->id();
          $user = \Drupal\user\Entity\User::load($id);
          $node->field_engagiert_sich_bei->entity =  $user->field_meine_in->entity;
          // $entity_initiative = $user->field_meine_in->entity;
          // Load node initiative
          //$node_initiative = $node_storage->load($entity_initiative->id());
          // write Tätigkeitsbereiche in offene Stelle
          //foreach($node_initiative->field_taetigkeitsbereich_der_ini as $taet){
          //$node->field_taetigkeitsbereich[] = $taet ->entity;
          //}
          //$node->field_kontakt_offene_stelle =  $node_initiative->field_email;
          $node->save();
  }
}
