<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
/**
 * Form alter for creation of "offene Stelle"
 */
function form_initia_form_node_initiativen_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //drupal_set_message('test1');
  //$form['field_initiative']['#disabled']= TRUE;
  //$form['field_beschreibung_stelle']['#title'] = t('Beschreibung');
  $form['revision_information']['#access'] = FALSE;
  $form['field_beschreibung_stelle']['#title'] = 'OMG';
  //$form['field_beschreibung']['#type'] = 'textarea';
  // Modification for the form with the given form ID goes here. For example, if
  // FORM_ID is "user_register_form" this code would run only on the user
  // registration form.

  // Add a checkbox to registration form about agreeing to terms of use.
  //$form['terms_of_use'] = [
  //  '#type' => 'checkbox',
  //  '#title' => t("I agree with the website's terms and conditions."),
  //  '#required' => TRUE,
  //];
}

// Write initiative into user field
function form_initia_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'initiativen') {
          $node_storage = \Drupal::entityManager()->getStorage('node');
          // Loading the node initiativen.
          $node = $node_storage->load($entity->id());
          // Get node title
          //$title_initiative = $node->get('title')->value;
          // Get user
          $user = \Drupal::currentUser();
          $id=$user->id();
          $user = \Drupal\user\Entity\User::load($id);
          $user->field_meine_in->entity =  $node;
          $user->save();
  }
}








